import { Link, createFileRoute } from "@tanstack/react-router";
import { ArrowUpRight } from "lucide-react";
import { CtaBand, PageIntro } from "@/components/page-primitives";
import { services, serviceGroups } from "@/lib/site-data";

export const Route = createFileRoute("/services/")({ component: ServicesPage });

function ServicesPage() {
  return <div><PageIntro eyebrow="Capabilities // BITS.go" title="Everything you need to move with confidence." copy="One connected partner for digital products, brand, visibility, intelligent automation, and the technology that keeps it all moving." /><section className="py-20 sm:py-28"><div className="mx-auto max-w-7xl px-5 sm:px-8"><div className="space-y-20">{serviceGroups.map((group) => <div key={group.label}><div className="mb-8 flex flex-col gap-3 border-b border-border pb-5 sm:flex-row sm:items-end sm:justify-between"><div><p className="eyebrow text-accent">{group.label}</p><h2 className="mt-3 text-3xl font-extrabold tracking-[-0.04em] sm:text-5xl">{group.title}</h2></div><p className="max-w-sm text-sm leading-6 text-muted-foreground">{group.serviceSlugs.length} connected capabilities.</p></div><div className="grid gap-4 md:grid-cols-2">{group.serviceSlugs.map((slug) => { const service = services.find((item) => item.slug === slug); if (!service) return null; return <Link key={service.slug} to="/services/$service" params={{ service: service.slug }} className="group border border-border bg-card p-6 transition-colors hover:border-accent sm:p-8"><div className="flex items-start justify-between gap-5"><span className="font-mono text-xs text-accent">{service.number} // {service.category}</span><ArrowUpRight size={17} className="text-muted-foreground transition group-hover:-translate-y-1 group-hover:translate-x-1 group-hover:text-accent" /></div><h3 className="mt-14 text-2xl font-bold">{service.title}</h3><p className="mt-3 max-w-lg text-sm leading-7 text-muted-foreground">{service.short}</p></Link>; })}</div></div>)}</div></div></section><CtaBand title="Not sure which service fits? Start with the business problem." copy="You can also consult the BITS.go AI business guide before you speak with our team." /></div>;
}